### PR TITLE
Create 100-IPFS-mobile-design-guidelines

### PR DESCRIPTION
**Pull request by jkosem**

### CODE REVIEW

**Comment by renrutnnej** [comment]
Tentatively slating this for a Wed-Thurs release this week

**Comment by jkosem** [comment]
@renrutnnej Thanks. If you need anything else let me know. I know some changes may have been lost before.

**Comment by autonome** [comment]
Old PR is #438. I'll copy the updates over.

**Comment by autonome** [comment]
Post updated, and I uploaded all the assets into static/100-mobile-design-guidelines.

The images might need the old school centering. @renrutnnej let's review on publish day.

**Pull request merged**
