### PR TITLE
post: ann ipfs camp

### PR DESCRIPTION
**Pull request by daviddias**
//cc @cwaring @olizilla @angiemaguire

### CODE REVIEW

**Comment by olizilla** [comment]
@daviddias wanna merge master up in here to  get that sweet pre-deploy preview?

**Comment by daviddias** [comment]
@olizilla of course! :D

**Comment by daviddias** [comment]
@angiemaguire, @cwaring preview is here \o/ https://ipfs.io/ipfs/QmX68GsR7PAavSKAowC7ZoTjiCmo8HFCfxwyaeBHEuqWy9/72-ann-ipfs-camp/

**Comment by olizilla** [comment]
Can has title that fits in 1 line?

screenshot 2019-02-28 at 11 09 06

**Pull request merged**
