### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by lgierth**
@diasdavid sorry for the big diff, while fixing the image links (absolute => relative) I also fixed the other links to be `//` instead of `http[s]://`

It should resolve at https://ipfs.io/ipns/blog.ipfs.io any minute...

### CODE REVIEW

**Comment by lgierth** [comment]
In the meantime: https://ipfs.io/ipfs/QmbF2z6apHrFgdRYarqtBAR7CwunbXwhSNjpx6JWMzJz3t"

**Comment by lgierth** [comment]
Okay works now. Also up here now: https://ipfs.io/blog/, no redirect yet though -- gonna take care of that soon

**Comment by RichardLitt** [comment]
@lgierth What needs to be done for this to be closed?

**Comment by diasdavid** [comment]
It seems the code on this PR was never merged, can we get a description of what was the route we took for it?

**Comment by lgierth** [comment]
Mh a few of the changes are still good to go I guess. The Makefile change is obsolete by now. Especially the readme note and dnslink-deploy dependency are good.

**Comment by lgierth** [comment]
Yeeaah... let me reopen this so I can assign it

**Comment by RichardLitt** [comment]
@lgierth what is up with this?

**Pull request closed without merging**
