### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by diasdavid**
@jbenet feedback

- https://github.com/ipfs/blog/pull/10#issuecomment-163574032
- https://github.com/ipfs/blog/pull/10#issuecomment-163578010

Action items:

- [x] remove codecs blog post
- [ ] add narration to the video demo
- [x] verify that there is no copyright on the 'Iberia from space' image
- [ ] use ipfs-update to simplify the dev0.4.0 instructions, @whyrusleeping 
- [x] fix "a claim like "there is no way for the list to be compromised" is waaaaay too strong -- there could be a cryptographic break, or a problem in our protocols or implementations, how about: "This list is fetched and kept up to date through IPNS. This ensures secure distribution, as IPNS records are signed and validated with the publisher's private key.""
- [x] fix "maybe "in the part of the network you are currently in" --> "the network you are currently in" ("part of" suggests distance/network-diameter problems)"
- [x] fix " "IPFS would be able to find it through Peer and Content Routing (with a DHT)." --> "IPFS would be able to find it through its Peer and Content Routing (e.g. with a DHT).""
- [x] fix ""Through cryptographic hashing -- the IPFS strategy to find, deliver and check that the content it received was what was requested -- you can always be sure that what you are running was what you were looking for." this line implies that "cryptographic hashing" is a strategy for finding and delivering content. it is not, we use "cryptographic hashing" as part of the strategy. how about: "Just like git, IPFS verifies the content received using cryptographic hashing, making sure it is exactly what was requested -- you can always be sure that what you are running is what you asked for.""

### CODE REVIEW

**Comment by diasdavid** [comment]
Not copyrighted

http://earthobservatory.nasa.gov/IOTD/view.php?id=76777
> The International Space Station Program supports the laboratory as part of the ISS National Lab to help astronauts take pictures of Earth that will be of the greatest value to scientists and the public, and to make those images freely available on the Internet

**Comment by diasdavid** [comment]
I will add narration to the video when I get back home later today and there is silence (sad I can't use my mic cause I didn't brought it with me)

**Comment by jbenet** [comment]
re image -- ok http://earthobservatory.nasa.gov/ImageUse/

**Comment by jbenet** [comment]
:+1: thanks @diasdavid

**Comment by diasdavid** [comment]
I've added narration https://vimeo.com/147968322 (using the same URL, because vimeo is awesome! )

**Comment by jbenet** [comment]
@diasdavid great narration!! in the very end, we kinda lose the point, i think we need to build up the moment of truth, and tell the user what they're seeing. Could you add a couple of narration sentences?

maybe:
- at `1:20` "now, let's try to install a module, disconnected from the internet"
- at `1:24` "I'll physically unplug my uplink, to shut off access to the internet. You can see the ping stops"
- at `1:36` "now, the moment of truth: let's install the module while offline" (could have a drumroll in the background :D) 
- at `1:48` [_excited!_] "that's it! we got the module from the other computer in our local network! I hope you enjoyed this demo ... (etc)" (ok if you talk past the end, just freeze the screen)

**Pull request merged**
