### PR TITLE
3 blog posts

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Proofing "Stellar" blogpost now.

**Comment by diasdavid** [comment]
@RichardLitt has finished the proofreads, @lgierth everything is good for merge :)

**Comment by jbenet** [comment]
hey guys, could you wait for an ok from me before shipping out blog posts? since the blog will be our loudspeaker to the whole world, i want to keep a certain focus and also level of quality. call me a curator! And, not that these posts arent good-- they are. i want to make sure i'm aware of the communications being shipped out, and the order. We will build a following to this blog, and it is important to carefully curate the readers' attention. It will also be good to get @kyledrake's feedback before shipping them. we can build a backlog of posts and ship them out as we choose them.

---

@diasdavid

- [ ] i dont think https://ipfs.io/blog/2-idempotent-encoder-decoder/ makes sense for the IPFS blog. we should keep the ipfs blog ipfs focused, not random cs stuff.
  - To give some direct feedback, it's very much a personal discovery type of post, which ignores Coding Theory and Programming Languages (PL) Theory. it makes sense for a personal blog -- which traces your history as you research and discover and think about things -- but not for "The Official IPFS Blog", which represents the whole IPFS community. IPFS is a thing that very smart PL people are following and want to use (for implementing CRDTs, LVars, replicators(?)). But if they saw this post pushed as "an official representation of the level of PL theory understanding of the IPFS team", they would rightfully be very concerned.
- [ ] on numbering, @kyledrake's other post was 2, so removing the encoder/decoder one should allow that one to merge into the right order.

**Comment by jbenet** [comment]
(hit enter too soon)

@diasdavid 

- **Both the ipscend and stellar module management are great!! :) :+1: **
- [ ] can you verify the image of the world in https://ipfs.io/blog/4-registry-mirror/ is CC-by or you have rights to use + distribute it? (i've been keeping my use of images very kosher with copyright, to the best result of my looking. some may have escaped, but just be aware and try to make sure licensing is solid.
- [ ] can we use `ipfs-update` to simplify the dev0.4.0 instructions? (ask @whyrusleeping for help) 
- [ ] a claim like "there is no way for the list to be compromised" is waaaaay too strong -- there could be a cryptographic break, or a problem in our protocols or implementations, how about: "This list is fetched and kept up to date through IPNS. This ensures secure distribution, as IPNS records are signed and validated with the publisher's private key."
- [ ] maybe "in the part of the network you are currently in" --> "the network you are currently in" ("part of" suggests distance/network-diameter problems)
- [ ] "IPFS would be able to find it through Peer and Content Routing (with a DHT)." --> "IPFS would be able to find it through its Peer and Content Routing (e.g. with a DHT)."
- [ ] "Through cryptographic hashing -- the IPFS strategy to find, deliver and check that the content it received was what was requested -- you can always be sure that what you are running was what you were looking for." this line implies that "cryptographic hashing" is a strategy for finding and delivering content. it is not, we use "cryptographic hashing" as _part of_ the strategy. how about: "Just like git, IPFS verifies the content received using cryptographic hashing, making sure it is exactly what was requested -- you can always be sure that what you are running is what you asked for."
- [ ] the demo video _really, really_ needs narration. I only know what's going on because i know what's going on.

**Comment by diasdavid** [comment]
>  i dont think https://ipfs.io/blog/2-idempotent-encoder-decoder/ makes sense for the IPFS blog. we should keep the ipfs blog ipfs focused, not random cs stuff. 

ok, sounds good ( I had it tagged with IPFS since it came from the CBOR discussions, as it is referenced).

Since this already got merged, I'll submit a separate PR with your proposed changes :)

**Pull request merged**
