### PR TITLE
wip: post on debugging go-ipfs with delve in code

### PR DESCRIPTION
**Pull request by olizilla**
More to do, but this is the gist. I had a nice experince with my first small PR to go-ipfs and using delve and code really helped me feel confident that my changes were doing what I thought they would.

also wanted to test out the new dweb.link preview urls
see: https://github.com/ipfs-shipyard/ipfs-dns-deploy/pull/7

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
@cwaring check out that ipfs preview link ☝️

**Comment by hugomrdias** [comment]
Love it ipfsify all the things 🤩

**Comment by cwaring** [comment]
Smooth as *butter emoji*

**Comment by jessicaschilling** [comment]
Closing: stale PR, and migration to new https://github.com/ipfs/ipfs-blog nearly complete.

**Pull request closed without merging**
