### PR TITLE
Decentralized real-time collaborative conflict free editing in the browser using js-ipfs and CRDTs

### PR DESCRIPTION
**Pull request by pgte**
…iting in the browser using js-ipfs and CRDTs

### CODE REVIEW

**Comment by pgte** [comment]
@diasdavid looking good, thanks! 👍

**Comment by diasdavid** [comment]
Let's publish this one Mon/Tue :)

**Comment by diasdavid** [comment]
Let's release tomorrow, Tuesday!

**Comment by mishmosh** [comment]
🌟

**Comment by diasdavid** [comment]
Published, twitted and reddited! 🚀

https://twitter.com/IPFSbot/status/892513418795769856
https://www.reddit.com/r/ipfs/comments/6qzu0c/decentralized_realtime_collaborative_documents/

Awesome work @pgte and thank you for reviewing every iteration @mishmosh !

**Pull request merged**
