### PR TITLE
Ethereum DevCon2 Post

### PR DESCRIPTION
**Pull request by RichardLitt**
# What

We should have a post after DevCon 2. 
# How

This should have a summary of our talks, as well as a roundup of the conference in general. A good example of a long roundup can be found on this [ScotlandJS](https://medium.com/@YLDio/scotlandjs-2016-69ed8a588161#.pvy98q2y1) Summary I wrote for YLD, after they gave me a free ticket to go. To make it easier for you - @jbenet, @diasdavid, @whyrusleeping, @haadcode, and @jesseclay - to write this up after, I am posting the skeleton here before. Ideally, each time you go to a talk, we can have a short summary - a few sentences - dropped in here after, which will help us make a cohesive story out of everything.

Of course, we can talk about how to do this! What I want to make sure is that we don't end up in a state where we have nothing written at the end of the conference, and we're all expected to walk away with some bright shiny post.

What're your thoughts?

### CODE REVIEW

**Comment by jbenet** [comment]
- We should aim to livetweet the event
- We should have an epic write up after, as we intended to do for DWS.

**Comment by RichardLitt** [comment]
@flyingzumwalt raised a very good point: it would be great if we could have the demos written up as comprehensive blogposts _before_ the event, so that we can refer to them in the event, and so that we don't need to scramble to write them afterwards. This will help us plan out our demos, too. How do you feel about this, everyone?

**Comment by haadcode** [comment]
I don't have a presentation yet. I probably won't until next week.

**Comment by mishmosh** [comment]
No longer timely.

**Pull request closed without merging**
