### PR TITLE
Explains the Files API a little bit more

### PR DESCRIPTION
**Pull request by noffle**
A big connection I really wanted to make sure people made was that the Files
API produces a sequence of immutable snapshots of a filesystem, and that each
snapshot can be extracted and used like any other IPFS object. Hopefully I've
illustrated this here!

### CODE REVIEW

**Comment by dignifiedquire** [comment]
lgtm

**Comment by jbenet** [comment]
LGTM

**Comment by jbenet** [comment]
This still needs to be published. i'll do it tomorrow. unless @lgierth gets to it first

**Comment by jbenet** [comment]
actually @whyrusleeping can you review too?

**Comment by noffle** [comment]
Published: https://ipfs.io/ipfs/QmWQ5BwExewgJ6SkJoTjhfD1Z17EhyjvsFERmUoifd79LZ/

I can publish-to-domain if I can get an auth token.

**Pull request merged**
