### PR TITLE
Update the first blog post with the IPNS address

### PR DESCRIPTION
**Pull request by llopv**

### CODE REVIEW

**Comment by RichardLitt** [comment]
If we're editing this post, you can just remove the struck-through text and the date about editing. But I'm not sure this post should be edited - @lgierth, do you know?

**Comment by lgierth** [comment]
Yes just make it https://ipfs.io/ipns/blog.ipfs.io, and remove the date and struck-through text. Sorry for the late reply.

**Comment by llopv** [comment]
I amended the commit with the required changes.

**Comment by diasdavid** [comment]
has merge conflicts. @llopv wanna fix it?

**Comment by daviddias** [comment]
applied with https://github.com/ipfs/blog/commit/a967c550bc1834277986fdb2d574b2832db31ab1

**Pull request closed without merging**
