### PR TITLE
Create new post for IPFS Mobile Design Guidelines

### PR DESCRIPTION
**Pull request by jkosem**
Here is the new blog post for the completed mobile design guidelines

### CODE REVIEW

**Comment by renrutnnej** [comment]
Thank you @jkosem! 

@autonome is there any type of visual from this work that we can use for a blog header in the index view? If not, we have a generic IPFS header to use.

**Comment by autonome** [comment]
@renrutnnej Hm, let me grab one of the visuals from the guide and mash up something.

**Comment by autonome** [comment]
Er, actually this PR deletes the ION post for some reason... need to remove that change.

**Comment by jkosem** [comment]
@autonome Closed.

**Comment by jkosem** [comment]
@autonome Should I delete the branch as well? Also, let me know if and when to redo the PR and that.

**Pull request closed without merging**
