### PR TITLE
Blog picture list

### PR DESCRIPTION
**Pull request by johnnymatthews**
### [Click here to see the preview](https://bafybeibal3m3lwtph2beo42mwol2oar4hqda3kkkvzhe54kbiveghtpkku.ipfs.dweb.link/).

---

This PR:

1. Addresses #295.
1. Adds images to all blog posts on the _list_ page.
1. Adds pagination logic and markup using existing CSS.
1. Displays up to 10 posts per page.

Images are controlled by a `header_image` variable within the front-matter of each post:

```markdown
---
date: 2019-09-30
url: 070-js-ipfs-0-38
title: js-ipfs 0.38.0 released
author: Alex Potsides
header_image: 070-js-ipfs-0-38.png
---
```

Header images are stored in `static/header_images`.

If no `header_image` variable is present in the front-matter, Hugo displays a placeholder image `static/header_images/blog-placeholder.png`.

Regular blog post placeholder.

If the page title contains `IPFS Weekly` Hugo displays a placeholder image `static/header/ipfs-weekly-placeholder.png`. This placeholder is 100% **not** on-brand.

Absolutely not on-brand placeholder.

---

### Todos

- [x] Different text for IPFS Weekly snippets.
- [x] Lower font-weight for titles.
- [x] Don't duplicate same JS-IPFS/LibP2P images. Use one placeholder and add if(js-ipfs) logic.
- [x] Add section to `#create-a-new-blog-post` on how to add a header image.
- [x] Increase post title font to 24px.
- [x] Add 8px padding between image and post title.
- [x] Decrease padding between post title and post snippet to 12px.

### CODE REVIEW

**Comment by momack2** [comment]
Nice! So much better! <3

Question - could we choose different text for the IPFS Weekly descriptions? Right now it just grabs the same intro every time - which isn't super useful. Can we either have a customized description field that we can go back and update with little recaps, or grab the content of the "latest" section (formatted something like "Latest highlights from IPFS: <section>, <headers>") so that this more clearly states what's new?

**Comment by johnnymatthews** [comment]
@momack2: I'm sure there's a hacky way to automate this, but it's beyond my Hugo hacking skills. Instead, we could add another variable into the front-matter for each IPFS Weekly. Something like:

```markdown
---
ipfs_weekly_snippet: IPFS docs beta went live, collaborative clusters are here, Go-IPFS 0.4.23 released, ipfs-update updated!
---
```

@alanshaw: I just threw a random image together for the IPFS Weekly, just a placeholder for now. I believe @renrutnnej is asking the [Design Team to create a fancy one](https://github.com/ipfs/blog/issues/295#issuecomment-607878694).

@alanshaw: My logic for having multiple identical image files (for JS-IPFS, and LibP2P) was to make it easier to manually check that each post has a corresponding image. I didn't think it'd be an issue since IPFS will use the same hash for each image anyway. Saying that, we could throw some more logic into the `index.html` page so that it checks to see if a post title contains `js-ipfs-X.XX`.

**Comment by momack2** [comment]
I'd like to avoid any special casing things based on titles or substrings - that might be hacky/brittle in the long run. What about we just add two new fields to the metadata for all posts: image and snippet. We can easily dedupe by just pointing to the same image file in the metadata - which gives us more flexibility for special cases while still allowing us to efficiently update an image if needed. WDYT?

**Comment by johnnymatthews** [comment]
Works for me. So there's two new fields that need to be in each post. `snippet` and `header_image`. Easy enough. If there's no `snippet` variable found, we can just take whatever's at the top of the blog post. That way there's no empty space or anything.

**Comment by johnnymatthews** [comment]
That should do it! New sections added to the README, images no longer duplicated, snippets now available, and lower font-weight for post links.

**Comment by momack2** [comment]
Looks amazing.  A few small UX tweaks (I am not a visual designer) would be to increase the font size of the blog titles to 24px (while keeping the dates at 18px), put another 8px of padding above the headers below the image), and decrease the padding between the header and the text to 12px (from 20px).
image

**Comment by johnnymatthews** [comment]
Tweaks added. I'm not 100% fluent with Less, so someone with actual front-end chops might want to look at my code here.

**Comment by momack2** [comment]
Changes look awesome. Discovered one more weirdness on a really large screen: 
Screen Shot 2020-04-10 at 7 44 28 PM

Looks like the max image size defaults to 250px by 500px instead of continuing to scale once the column is wider than that. We should either limit the column width, or make the image scale up.

**Comment by johnnymatthews** [comment]
Nice catch @momack2. 814ac8c fixes this setting the `min-width` of the post header images to `100%`. I did a quick check and this doesn't affect any other images on the site.

**Pull request merged**
