### PR TITLE
Post: Announcing js-ipfs 0.27 Release

### PR DESCRIPTION
**Pull request by diasdavid**
@mishmosh can I get your review here? Can't wait to make this release :D

### CODE REVIEW

**Comment by diasdavid** [comment]
image

**Comment by diasdavid** [comment]
Release done, now I just a review on the copy here and ready to publish!

**Comment by diasdavid** [comment]
Ok, to not lose momentum, I'll go ahead and publish it.

**Comment by mishmosh** [comment]
Sorry about the delay, I think this accidentally got muted with some other notifications. Glad you kept the momentum up.

**Pull request merged**
