### PR TITLE
Added IPFS Weekly 7

### PR DESCRIPTION
**Pull request by RichardLitt**
Thanks! @lgierth

### CODE REVIEW

**Comment by RichardLitt** [comment]
Ran make publish, `pinned QmXkrrx3iFXq5qFGP2qRb7m4UoJ1YaeRdmfyEqMyMEuN8i recursively.` Should I run `make publish-to-domain` too?

**Comment by lgierth** [comment]
Where did you pin that?

**Comment by RichardLitt** [comment]
Just normally?

**Comment by lgierth** [comment]
On your local machine? Was just wondering because I wasn't able to fetch it from the gateways or anything else in the v04x network. I publish-to-domain'd it as QmWfJ2JA4NSMZfGRSApbsM2w2khZCSWQ4pgpRQXREoWtBe.

**Comment by RichardLitt** [comment]
Huh, strange. Maybe I disconnected my daemon before it got pinned? 

let's talk in New York about how to do this, together. I want to be able to publish this myself, and to know the ins and outs as much as I need to. Sound good?

**Pull request merged**
