### PR TITLE
Hugo refactor

### LINKED ISSUE #107: RSS Feed only displays Oldest 20 items
metalsmith-feed by default only adds 20 item to the rss feed. unfortunately it grabs the 20 oldest instead of the 20 newest. 
Also limit doesn't properly take false to remove this.

A workaround could be to add a arbitrarily large limit to the feed.
`.use(feed({'collection': 'posts', 'limit': 1e9}))`

Or reversing the collection this would place most recent 20 in the feed, but it also reverses blog page order
```
  .use(collections({
    posts: {reverse: true}
  }))

```
~~Unless there is a way to reverse the collection order i haven't seen,~~ I'm not exactly a metalsmith wizard.
I plan to post an issue on hurrymaplelad/metalsmith-feed about this as well.

### PR DESCRIPTION
**Pull request by alanshaw**
This PR refactors the blog to use hugo as its build tool.

This is ~~95%~~ 100% complete and may be merged if you wish ✨ 

Remaining things to do:

* ~~Add back RSS feed~~
* ~~Check static assets are working as expected~~
* Deploy step
* ~~General clean ups~~

🚀 

Also bonus unintended fixes #107

### CODE REVIEW

**Comment by diasdavid** [comment]
Wooop! What a breath of fresh air for our blog :)

@alanshaw I just checked out and noticed that the styles from ipfs.io haven't been applied yet, could you add that to the list of remaining tasks? Thanks!

**Comment by alanshaw** [comment]
@diasdavid this is good to go now!

1. Deploy step coming as a separate PR
2. As discussed with @olizilla new styles coming in next sprint

**Comment by diasdavid** [comment]
Hey @alanshaw! Here are a couple of comments, nothing big. Awesome! 🌟

- [ ] README.md needs to be updated to match new deploy set up
- [ ] README.md should inform the user that the webpage is available only in `/blog`. Getting a 404 is misleading

----- 

Do we node.js for this? I believe package.json can be remove and everything can be done through the Makefile

**Comment by alanshaw** [comment]
@diasdavid 

1. I was anticipating the README (for new deploy info) would be updated in the PR we send for deployment
2. I'll get that fixed
3. I didn't know if we still needed the `dnslink-deploy` module (in `devDependencies` of `package.json`) for the deployment or not so I left it in - one for the deploy PR to remove if necessary I think

**Comment by diasdavid** [comment]
Ok. Will merge this one now. Can you open the Deploy PR after and add the items above?

**Comment by arturi** [comment]
Sorry to budge in, just curious, why Hugo over Metalsmith?

**Pull request merged**
