### PR TITLE
Containers at Hyperspeed - Container Camp London

### PR DESCRIPTION
**Pull request by RichardLitt**
Part of the transcription pipeline.

### CODE REVIEW

**Comment by RichardLitt** [comment]
@jbenet Did the first of these; is there anything you else you would like me to do for these transcriptions before I ship? I went through the transcript while listening to the video, made manual edits, and then moved the file over here, adding the video file and a short paragraph to the page.

**Comment by lgierth** [comment]
The images need to be added to the same directory as index.md, and then just referenced as is, e.g. `some img`

**Comment by RichardLitt** [comment]
@lgierth Should be fixed now.

**Comment by skylarnorris** [comment]
This LGTM but someone else may want to weigh in on the blog end.  @em-ly?

**Comment by diasdavid** [comment]
_Closing ancient posts that never got posted._

**Pull request closed without merging**
