### PR TITLE
rename index.html to _index.html

### LINKED ISSUE #155: Build issues with latest Hugo
Hugo  v0.31.1 is used by the CI setup and it works [fine](https://user-images.githubusercontent.com/157609/38552945-060d3172-3cbe-11e8-82be-6f5bbc907d77.png).

However if I try to build it locally with the latest Hugo (v0.38.2) it produces no posts:

> screenshot-2018-4-10 ipfs blog 1

I did not look into details, as the quick workaround was to just use [v0.31.1](https://github.com/gohugoio/hugo/releases/v0.31.1) for this repo.

### PR DESCRIPTION
**Pull request by Stebalien**
fixes building with the latest hugo

fixes #155

### CODE REVIEW

**Comment by Stebalien** [comment]
Broken on CI, needs https://github.com/ipfs/ci-websites/pull/4.

**Comment by daviddias** [comment]
We've locked to a previous Hugo version. All good now :)

**Comment by Stebalien** [comment]
Not "all good now". We shouldn't lock to an old version.

**Comment by Stebalien** [comment]
(it'll confuse anyone trying to build this website locally)

**Comment by Stebalien** [comment]
I've updated hugo in the package.json file so this should no longer depend on [ipfs/ci-websites#4](https://github.com/ipfs/ci-websites/pull/4)

**Comment by Stebalien** [comment]
(but thanks for clearing out old PRs)

**Comment by daviddias** [comment]
> We shouldn't lock to an old version.

@Stebalien did you test building it with latest?

**Comment by Stebalien** [comment]
No, it doesn't. You know, I give up. This isn't worth it.

**Pull request closed without merging**
